# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
Movie.delete_all

Movie.create!(title: "The Godfather", overview: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", poster_url: "https://image.tmdb.org/t/p/original/b7GG5g9wPNTXYrYP2Ll3uZbFuBx.jpg", rating: 9.2)
Movie.create!(title: "The Dark Knight", overview: "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.", poster_url: "https://image.tmdb.org/t/p/original/rKkXI5kGpNE87I5Ck07UP2UfhzB.jpg", rating: 8.4)
Movie.create!(title: "Inception", overview: "A thief who enters the dreams of others to steal secrets from their subconscious is given the chance to have his criminal record erased if he can successfully perform an inception.", poster_url: "https://image.tmdb.org/t/p/original/x9okfU0Xln3IZivn9vLFelJ0Lji.jpg", rating: 8.8)
Movie.create!(title: "Forrest Gump", overview: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal, and other historical events unfold from the perspective of an Alabama man with an extraordinary life story.", poster_url: "https://image.tmdb.org/t/p/original/xv72qlnNRewrI0fjPoDeB6l3F5d.jpg", rating: 8.8)
Movie.create!(title: "The Shawshank Redemption", overview: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", poster_url: "https://image.tmdb.org/t/p/original/q6pHz9alELf5hFQ1UqOqBszc8Wv.jpg", rating: 9.3)
Movie.create!(title: "Schindler's List", overview: "In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.", poster_url: "https://image.tmdb.org/t/p/original/1wq4vZnvv1vA1LCdoA7qaImDsFY.jpg", rating: 8.9)
Movie.create!(title: "The Matrix", overview: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.", poster_url: "https://image.tmdb.org/t/p/original/5rkNfExXUvnfrf1tFzWvKJOM4e6.jpg", rating: 8.7)
Movie.create!(title: "Gladiator", overview: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.", poster_url: "https://image.tmdb.org/t/p/original/6scz00R8sGz4NwXefQhIJNsda5B.jpg", rating: 8.5)
Movie.create!(title: "The Lion King", overview: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.", poster_url: "https://image.tmdb.org/t/p/original/6WBuJ5vFh7fS5HX2vUqau4G6f14.jpg", rating: 8.5)
Movie.create!(title: "Star Wars: Episode V - The Empire Strikes Back", overview: "After the rebels are overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued by Darth Vader.", poster_url: "https://image.tmdb.org/t/p/original/9ExFh3WGB6mOtK3mtoUebzAiV2G.jpg", rating: 8.7)
Movie.create!(title: "Pulp Fiction", overview: "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", poster_url: "https://image.tmdb.org/t/p/original/1l2RlkUedtnOXf4VccMmn3KhET9.jpg", rating: 8.9)
Movie.create!(title: "Fight Club", overview: "An insomniac office worker and a soap salesman form an underground fight club that evolves into much more.", poster_url: "https://image.tmdb.org/t/p/original/5db0kl8JxhZB7j6ekglttk9W2GE.jpg", rating: 8.8)
Movie.create!(title: "The Lord of the Rings: The Fellowship of the Ring", overview: "A young hobbit, Frodo Baggins, is recruited to join a fellowship of travelers as they embark on a mission to destroy the One Ring and defeat the Dark Lord Sauron.", poster_url: "https://image.tmdb.org/t/p/original/kqFDibGjQzyRO91slk9MvHOqu7d.jpg", rating: 8.8)
Movie.create!(title: "The Silence of the Lambs", overview: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.", poster_url: "https://image.tmdb.org/t/p/original/2RpxF8azJeQavkYMIhzADy8uX2g.jpg", rating: 8.6)
Movie.create!(title: "The Departed", overview: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in Boston.", poster_url: "https://image.tmdb.org/t/p/original/pGG2ovp08lgV9B59gZaWdaHq7RG.jpg", rating: 8.5)
Movie.create!(title: "The Prestige", overview: "Two magicians engage in a bitter rivalry, with each attempting to best the other's tricks and unveil each other's secrets.", poster_url: "https://image.tmdb.org/t/p/original/cJshJQofFfsAZZ3d5aHhC06jpHL.jpg", rating: 8.5)
Movie.create!(title: "Back to the Future", overview: "Marty McFly, a teenager, is sent 30 years into the past in a time machine built by his close friend, the eccentric scientist Dr. Emmett Brown.", poster_url: "https://image.tmdb.org/t/p/original/qHEWcbglFdZoc2MbkAkBZfGk8At.jpg", rating: 8.5)
Movie.create!(title: "The Green Mile", overview: "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments.", poster_url: "https://image.tmdb.org/t/p/original/qXbZYwvVqYmyYl9uGEvliTe05g5.jpg", rating: 8.6)
Movie.create!(title: "Interstellar", overview: "A group of explorers must travel beyond this galaxy to discover whether humanity has a future among the stars.", poster_url: "https://image.tmdb.org/t/p/original/lahkmOnfWnqLgTkFZ4bU0Y2mtjq.jpg", rating: 8.6)
Movie.create!(title: "Se7en", overview: "Two detectives hunt a serial killer who uses the seven deadly sins as his modus operandi.", poster_url: "https://image.tmdb.org/t/p/original/gosT9d8BeCpaD5BICaFq8swCS7Q.jpg", rating: 8.6)
Movie.create!(title: "Goodfellas", overview: "The story of Henry Hill and his life in the Mafia, covering his relationship with his wife and his involvement with the mob.", poster_url: "https://image.tmdb.org/t/p/original/rnKZGmwO5whe17coQSmlE9yD7cV.jpg", rating: 8.7)
Movie.create!(title: "Avatar", overview: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.", poster_url: "https://image.tmdb.org/t/p/original/vfYChidT6f5JYppqFV4MbCj3HUl.jpg", rating: 7.8)
Movie.create!(title: "The Breakfast Club", overview: "Five high school students from different walks of life endure a Saturday detention under the supervision of an unorthodox teacher.", poster_url: "https://image.tmdb.org/t/p/original/iDN6YPnUzTckg6gdOhhOCrEXJb5.jpg", rating: 8.0)
Movie.create!(title: "Jaws", overview: "A great white shark terrorizes a small resort town, and a police chief, a marine biologist, and a professional shark hunter work together to catch it.", poster_url: "https://image.tmdb.org/t/p/original/2TeXc0jw7G9q8HRBopkvq5sQhxX.jpg", rating: 8.0)
Movie.create!(title: "A Clockwork Orange", overview: "In the future, a young man is arrested for a spree of delinquent acts and subjected to a controversial rehabilitation treatment.", poster_url: "https://image.tmdb.org/t/p/original/v8bK0gLTuVuFQpxvJksEDVAGcGG.jpg", rating: 8.3)
Movie.create!(title: "Whiplash", overview: "A young drummer is pushed to the limit by an abusive instructor at a prestigious music conservatory.", poster_url: "https://image.tmdb.org/t/p/original/9uP70pOvkSeFz2d2WxNTTxOjka1.jpg", rating: 8.5)
Movie.create!(title: "12 Angry Men", overview: "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.", poster_url: "https://image.tmdb.org/t/p/original/yW0u3TYBh8InXw4xEKbo2b49ZLx.jpg", rating: 8.9)
Movie.create!(title: "The Pianist", overview: "A Jewish virtuoso pianist struggles to survive the devastation of the Warsaw Ghetto during World War II.", poster_url: "https://image.tmdb.org/t/p/original/4Qz63tD8y4AWYl9Tw7OKbPNHtGI.jpg", rating: 8.5)
Movie.create!(title: "The Truman Show", overview: "An insurance salesman discovers his entire life is actually a TV show.", poster_url: "https://image.tmdb.org/t/p/original/iiBpUg6IhZg7klEwSbVZtMXECpJ.jpg", rating: 8.1)
Movie.create!(title: "City of God", overview: "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.", poster_url: "https://image.tmdb.org/t/p/original/6eV1DAjo2VcsZTgIqY2N9uT1BY3.jpg", rating: 8.6)
